/**
 * Dynamic document compilers for RockPay Documents hub.
 * Tenancy uses a standardized Nigerian-style layout; not legal advice.
 */

export type TenancyVars = {
  landlordName: string;
  tenantName: string;
  propertyAddress: string;
  duration: string;
  rentAmount: string;
  /** Display date for agreement "made this…" */
  agreementDate: string;
  /** Lease commencement */
  startDate: string;
};

export type ConstitutionVars = {
  businessName: string;
  managerName: string;
  businessAddress: string;
  agreementDate: string;
};

function formatNairaPlain(amount: string): string {
  const n = Number(String(amount).replace(/,/g, ""));
  if (!Number.isFinite(n) || n <= 0) return amount || "[Rent Amount]";
  return n.toLocaleString("en-NG");
}

/** Residential Tenancy — standardized template with injected variables. */
export function compileResidentialTenancyAgreement(v: TenancyVars): string {
  const landlord = v.landlordName.trim() || "[Landlord Name]";
  const tenant = v.tenantName.trim() || "[Tenant Name]";
  const address = v.propertyAddress.trim() || "[Property Address]";
  const duration = v.duration.trim() || "[Duration]";
  const rent = formatNairaPlain(v.rentAmount);
  const made = v.agreementDate || "[Current Date]";
  const start = v.startDate || made;

  return `TENANCY AGREEMENT

THIS TENANCY AGREEMENT is made this ${made} BETWEEN ${landlord} (hereinafter called the "Landlord") of the one part AND ${tenant} (hereinafter called the "Tenant") of the other part.

WHEREAS the Landlord is the absolute owner of the property situated at ${address}.
WHEREAS the Tenant desires to take a lease of the premises and the Landlord agrees to grant same.

IT IS MUTUALLY AGREED AS FOLLOWS:

1. The Landlord hereby lets to the Tenant the property at ${address} for a term of ${duration} commencing on ${start} at the rent of ₦${rent} per annum.

2. The Tenant agrees to keep the interior of the premises in good and tenantable repair, reasonable wear and tear excepted.

3. The Tenant agrees not to alter the structure of the premises without the written consent of the Landlord.

IN WITNESS WHEREOF the parties have set their hands the day and year first above written.

______________________________          ______________________________
Landlord                                Tenant

Name: ${landlord}                       Name: ${tenant}
`;
}

export function compileBusinessConstitution(v: ConstitutionVars): string {
  const business = v.businessName.trim() || "[Business / Proprietor]";
  const manager = v.managerName.trim() || "[Manager / Partner]";
  const address = v.businessAddress.trim() || "[Business address]";
  const made = v.agreementDate || "[Current Date]";

  return `BUSINESS CONSTITUTION

This constitution is adopted this ${made} by ${business} ("the Business").

1. PURPOSE
The Business is established to carry on lawful trade and related activities in Nigeria.

2. MANAGEMENT
${manager} may assist in day-to-day management as agreed in writing between the parties.

3. REGISTERED ADDRESS
${address}

4. GENERAL
This document is a product template for operational convenience. Obtain professional legal review before reliance.
`;
}

/** Printable HTML wrapper for client-side print / download. */
export function documentToPrintableHtml(title: string, bodyText: string): string {
  const escaped = bodyText.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const paragraphs = escaped
    .split(/\n\n+/)
    .map((block) => {
      const lines = block.split("\n").join("<br/>");
      return `<p style="margin:0 0 1em; text-align:justify;">${lines}</p>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>${title.replace(/</g, "")}</title>
  <style>
    @page { margin: 2cm; }
    body {
      font-family: "Times New Roman", Times, serif;
      font-size: 12pt;
      line-height: 1.45;
      color: #111;
      max-width: 720px;
      margin: 24px auto;
      padding: 0 16px;
    }
    h1 {
      font-size: 16pt;
      text-align: center;
      letter-spacing: 0.06em;
      margin-bottom: 1.5em;
      text-transform: uppercase;
    }
    .footer {
      margin-top: 2em;
      font-size: 9pt;
      color: #555;
      border-top: 1px solid #ccc;
      padding-top: 0.75em;
    }
    @media print {
      body { margin: 0; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <h1>${title.replace(/</g, "")}</h1>
  ${paragraphs}
  <p class="footer">Generated by RockPay Documents · Not legal advice · ${new Date().toISOString().slice(0, 10)}</p>
  <script>
    // Auto-print only when opened via printDocument()
    if (location.search.indexOf("autoprint=1") !== -1) {
      window.onload = function () { window.print(); };
    }
  </script>
</body>
</html>`;
}

export function openPrintableDocument(title: string, bodyText: string) {
  const html = documentToPrintableHtml(title, bodyText);
  const w = window.open("", "_blank", "noopener,noreferrer,width=800,height=900");
  if (!w) {
    throw new Error("Allow pop-ups to print this document.");
  }
  w.document.open();
  w.document.write(
    html.replace("</body>", "") +
      `<script>window.onload=function(){window.print();}</script></body></html>`,
  );
  w.document.close();
}

export function downloadDocumentHtml(title: string, bodyText: string, filename: string) {
  const html = documentToPrintableHtml(title, bodyText);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".html") ? filename : `${filename}.html`;
  a.click();
  URL.revokeObjectURL(url);
}
