/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedPaymentsRouteImport } from './routes/saved-payments'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as CacRouteImport } from './routes/cac'
import { Route as NinRouteImport } from './routes/nin'
import { Route as TinRouteImport } from './routes/tin'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as VehicleRouteImport } from './routes/vehicle'
import { Route as SetupPinRouteImport } from './routes/setup-pin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminCareRouteImport } from './routes/admin.care'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminReconciliationRouteImport } from './routes/admin.reconciliation'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as HistoryTxIdRouteImport } from './routes/history.$txId'
import { Route as PaySlugRouteImport } from './routes/pay.$slug'
import { Route as PayCompleteRouteImport } from './routes/pay.complete'
import { Route as ProfilePersonalRouteImport } from './routes/profile.personal'
import { Route as ProfilePrivacyRouteImport } from './routes/profile.privacy'
import { Route as SupportTicketIdRouteImport } from './routes/support.$ticketId'
import { Route as WalletFundRouteImport } from './routes/wallet.fund'
import { Route as AdminCareTicketIdRouteImport } from './routes/admin.care.$ticketId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as HistoryTxIdReportRouteImport } from './routes/history.$txId.report'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedPaymentsRoute = SavedPaymentsRouteImport.update({
  id: '/saved-payments',
  path: '/saved-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CacRoute = CacRouteImport.update({
  id: '/cac',
  path: '/cac',
  getParentRoute: () => rootRouteImport,
} as any)
const NinRoute = NinRouteImport.update({
  id: '/nin',
  path: '/nin',
  getParentRoute: () => rootRouteImport,
} as any)
const TinRoute = TinRouteImport.update({
  id: '/tin',
  path: '/tin',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRoute = VehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPinRoute = SetupPinRouteImport.update({
  id: '/setup-pin',
  path: '/setup-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareRoute = AdminCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReconciliationRoute = AdminReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const HistoryTxIdRoute = HistoryTxIdRouteImport.update({
  id: '/$txId',
  path: '/$txId',
  getParentRoute: () => HistoryRoute,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCompleteRoute = PayCompleteRouteImport.update({
  id: '/pay/complete',
  path: '/pay/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePersonalRoute = ProfilePersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ProfileRoute,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => SupportRoute,
} as any)
const WalletFundRoute = WalletFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => WalletRoute,
} as any)
const AdminCareTicketIdRoute = AdminCareTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AdminCareRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const HistoryTxIdReportRoute = HistoryTxIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => HistoryTxIdRoute,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/saved-payments': typeof SavedPaymentsRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/cac': typeof CacRoute
  '/nin': typeof NinRoute
  '/tin': typeof TinRoute
  '/documents': typeof DocumentsRoute
  '/vehicle': typeof VehicleRoute
  '/setup-pin': typeof SetupPinRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/care': typeof AdminCareRouteWithChildren
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/wallet': typeof AdminWalletRoute
  '/history/$txId': typeof HistoryTxIdRouteWithChildren
  '/pay/$slug': typeof PaySlugRoute
  '/pay/complete': typeof PayCompleteRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/wallet/fund': typeof WalletFundRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/care/$ticketId': typeof AdminCareTicketIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/history/$txId/report': typeof HistoryTxIdReportRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/saved-payments': typeof SavedPaymentsRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/cac': typeof CacRoute
  '/nin': typeof NinRoute
  '/tin': typeof TinRoute
  '/documents': typeof DocumentsRoute
  '/vehicle': typeof VehicleRoute
  '/setup-pin': typeof SetupPinRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/care': typeof AdminCareRouteWithChildren
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/wallet': typeof AdminWalletRoute
  '/history/$txId': typeof HistoryTxIdRouteWithChildren
  '/pay/$slug': typeof PaySlugRoute
  '/pay/complete': typeof PayCompleteRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/wallet/fund': typeof WalletFundRoute
  '/admin': typeof AdminIndexRoute
  '/admin/care/$ticketId': typeof AdminCareTicketIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/history/$txId/report': typeof HistoryTxIdReportRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/saved-payments': typeof SavedPaymentsRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/cac': typeof CacRoute
  '/nin': typeof NinRoute
  '/tin': typeof TinRoute
  '/documents': typeof DocumentsRoute
  '/vehicle': typeof VehicleRoute
  '/setup-pin': typeof SetupPinRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/care': typeof AdminCareRouteWithChildren
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/wallet': typeof AdminWalletRoute
  '/history/$txId': typeof HistoryTxIdRouteWithChildren
  '/pay/$slug': typeof PaySlugRoute
  '/pay/complete': typeof PayCompleteRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/wallet/fund': typeof WalletFundRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/care/$ticketId': typeof AdminCareTicketIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/history/$txId/report': typeof HistoryTxIdReportRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/privacy'
    | '/profile'
    | '/saved-payments'
    | '/security'
    | '/services'
    | '/cac'
    | '/nin'
    | '/tin'
    | '/documents'
    | '/vehicle'
    | '/setup-pin'
    | '/signup'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/admin/activity'
    | '/admin/audit-logs'
    | '/admin/care'
    | '/admin/pricing'
    | '/admin/reconciliation'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallet'
    | '/history/$txId'
    | '/pay/$slug'
    | '/pay/complete'
    | '/profile/personal'
    | '/profile/privacy'
    | '/support/$ticketId'
    | '/wallet/fund'
    | '/admin/'
    | '/admin/care/$ticketId'
    | '/admin/users/$userId'
    | '/history/$txId/report'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/privacy'
    | '/profile'
    | '/saved-payments'
    | '/security'
    | '/services'
    | '/cac'
    | '/nin'
    | '/tin'
    | '/documents'
    | '/vehicle'
    | '/setup-pin'
    | '/signup'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/admin/activity'
    | '/admin/audit-logs'
    | '/admin/care'
    | '/admin/pricing'
    | '/admin/reconciliation'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallet'
    | '/history/$txId'
    | '/pay/$slug'
    | '/pay/complete'
    | '/profile/personal'
    | '/profile/privacy'
    | '/support/$ticketId'
    | '/wallet/fund'
    | '/admin'
    | '/admin/care/$ticketId'
    | '/admin/users/$userId'
    | '/history/$txId/report'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/privacy'
    | '/profile'
    | '/saved-payments'
    | '/security'
    | '/services'
    | '/cac'
    | '/nin'
    | '/tin'
    | '/documents'
    | '/vehicle'
    | '/setup-pin'
    | '/signup'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/admin/activity'
    | '/admin/audit-logs'
    | '/admin/care'
    | '/admin/pricing'
    | '/admin/reconciliation'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallet'
    | '/history/$txId'
    | '/pay/$slug'
    | '/pay/complete'
    | '/profile/personal'
    | '/profile/privacy'
    | '/support/$ticketId'
    | '/wallet/fund'
    | '/admin/'
    | '/admin/care/$ticketId'
    | '/admin/users/$userId'
    | '/history/$txId/report'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SavedPaymentsRoute: typeof SavedPaymentsRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  CacRoute: typeof CacRoute
  NinRoute: typeof NinRoute
  TinRoute: typeof TinRoute
  DocumentsRoute: typeof DocumentsRoute
  VehicleRoute: typeof VehicleRoute
  SetupPinRoute: typeof SetupPinRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRouteWithChildren
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRouteWithChildren
  PaySlugRoute: typeof PaySlugRoute
  PayCompleteRoute: typeof PayCompleteRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SavedPaymentsRoute: SavedPaymentsRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  CacRoute: CacRoute,
  NinRoute: NinRoute,
  TinRoute: TinRoute,
  DocumentsRoute: DocumentsRoute,
  VehicleRoute: VehicleRoute,
  SetupPinRoute: SetupPinRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRouteWithChildren,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRouteWithChildren,
  PaySlugRoute: PaySlugRoute,
  PayCompleteRoute: PayCompleteRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

// Child route type helpers (generated)
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cac': {
      id: '/cac'
      path: '/cac'
      fullPath: '/cac'
      preLoaderRoute: typeof CacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nin': {
      id: '/nin'
      path: '/nin'
      fullPath: '/nin'
      preLoaderRoute: typeof NinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin': {
      id: '/tin'
      path: '/tin'
      fullPath: '/tin'
      preLoaderRoute: typeof TinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle': {
      id: '/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof VehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
